export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const POST_ORDER = 'POST_ORDER_PRODUCTS';
export const FETCH_ORDERS = 'FETCH_ORDERS';
